import {
  Aperture,
  Award,
  BedDouble,
  BookOpen,
  Bus,
  Camera,
  Clapperboard,
  Clock,
  Compass,
  FileText,
  Film,
  Focus,
  FolderDown,
  GraduationCap,
  Grid2x2,
  HeartHandshake,
  Image as ImageIcon,
  Images,
  Layers,
  LayoutGrid,
  Leaf,
  MapPin,
  MessageSquare,
  Moon,
  Mountain,
  NotebookPen,
  Orbit,
  Package,
  Palette,
  Plane,
  ShieldCheck,
  Shirt,
  SlidersHorizontal,
  Sparkles,
  Sprout,
  Sun,
  Telescope,
  Thermometer,
  TrendingUp,
  Users,
  UsersRound,
  Utensils,
  Video,
  Wand2,
  type LucideProps,
} from 'lucide-react'

/**
 * Maps the icon-name strings stored in `lib/astrophotography-data.ts` to lucide
 * icons, so content stays plain data and components render the right glyph.
 */
const ICONS: Record<string, React.ComponentType<LucideProps>> = {
  Aperture,
  Award,
  BedDouble,
  BookOpen,
  Bus,
  Camera,
  Clapperboard,
  Clock,
  Compass,
  FileText,
  Film,
  Focus,
  FolderDown,
  GraduationCap,
  Grid2x2,
  HeartHandshake,
  Image: ImageIcon,
  Images,
  Layers,
  LayoutGrid,
  Leaf,
  MapPin,
  MessageSquare,
  Moon,
  Mountain,
  NotebookPen,
  Orbit,
  Package,
  Palette,
  Plane,
  ShieldCheck,
  Shirt,
  SlidersHorizontal,
  Sparkles,
  Sprout,
  Sun,
  Telescope,
  Thermometer,
  TrendingUp,
  Users,
  UsersRound,
  Utensils,
  Video,
  Wand2,
}

export default function AstroIcon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp = ICONS[name] ?? Sparkles
  return <Cmp {...props} />
}
